### PR TITLE
Nick Byrne transcript initialisation

### PR DESCRIPTION
**Pull request by schmico**
Initial commit to kick off nick-byrne-transcript.md

Thanks for all your work!

### CODE REVIEW

**Comment by schmico** [comment]
Submitting PR of my planned curriculum

**Comment by clarecorthell** [comment]
Godspeed - definitely make notes when you run into something that you realize you should instead omit. I ran into that occasionally _\*coughcoughadoop\*_

**Comment by schmico** [comment]
Haha thanks for the heads up - is that in reference to the swapping in of
EdX Spark over Hadoop?
Let me know if there's anything I can do to help :)

**Comment by clarecorthell** [comment]
Ask some people who actually work at companies via twitter!

**Pull request merged**
