### PR TITLE
Added video lectures for Maths, Algorithms and ML

### PR DESCRIPTION
**Pull request by mccajm**

### CODE REVIEW

**Comment by clarecorthell** [comment]
The OSDSM aggregates the best content or class for a given topic. Do you believe any of these classes are well organized and taught such that they should supplant the current material? For example, is Statistics 110 better in material, teaching, and design than Princeton Stats 1?

**Comment by mccajm** [comment]
I suppose the answer to that is personal opinion, but I followed all of the courses I added and prefer them to the existing courses.

**Comment by clarecorthell** [comment]
@mccajm Please make your case for them - it will take me a long time to get back to these courses to assess myself

**Comment by clarecorthell** [comment]
Closing while discussion continues

**Pull request closed without merging**
