### PR TITLE
scott-davis-transcript-2016

### PR DESCRIPTION
**Pull request by scdavis50**
My data science curriculum, studied and/or in progress.  Great repo.  Happy to contribute.

### CODE REVIEW

**Comment by clarecorthell** [comment]
Thanks for adding your curriculum! What's your study plan like? Transition, nights and weekends?

**Comment by scdavis50** [comment]
I left my previous job about a week ago for a number of reasons and have 
a 6 month non-compete, so right now I'm doing about 6-8 hours a day.

Once the kids get out of school I'll probably cut back to about 4 
hours/day but I'd like to be finished by July.

I'm also building some models that I'm targeting for completion in late 
August before I get back to work in October.

Thanks for this resource -- I'm happy to contribute some modifications 
but what a labor it must have been to assemble.

Thanks
Scott

**Comment by clarecorthell** [comment]
I'm impressed by your ambition, I'd be curious if the whole list fits in that time span. What kind of role are you looking at after that?

**Comment by scdavis50** [comment]
I'd agree that it's going to be tight.  I'm almost finished with the 
data science coursera specialization - I have one class + the capstone 
left. I used to a lot of heavy excel work and some programming in 
access, so it's not totally new and I've spent the last year working on 
my R skills so I feel like once I have that down the rest will go pretty 
quickly.

I've been talking with one of my competitors about a position in real 
estate consulting.  I'm looking to leverage data science tools/methods, 
etc in the real estate space.  The industry's been very slow to embrace 
technology and I believe that presents an opening.  For example my 
former company was a leading provider of data and the backend of their 
web platform runs in access 2.0.  I'm looking to build an optimization 
model for maximizing NPV in real estate developments, using the urban 
sim model to build forecast models for the major Texas metros and 
automate several of the standard studies that we do to run them as 
reports out of a python-gis standalone app.

What kind of work do you do with Luminant?

**Comment by clarecorthell** [comment]
Curious to hear any updates on your journey, @scdavis50!

**Pull request merged**
